#服务器端口
server:
  port: 8080
  servlet:
    context-path: /chefubao
spring:
  # mysql数据库配置信息
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.99.138.203:3306/chefubao?characterEncoding=utf-8&useSSL=false
    username: root1
    password: liu970908
  # redis 配置
  redis:
    database: 0
    host: 39.107.49.58
    port: 6379
    password: 123456
  # 文件图片路径映射
  mvc:
    static-path-pattern: ${image-path}/**
  resources:
    static-locations: file:${image-path}
# 图片上传地址
image-path: /home/image

#控制台打印sql配置信息
logging:
  level:
    com.sw.chefubao.mapper: debug   #对应的mapper包